### ISSUE TITLE
Error retrieving info from hub: 417

### ISSUE THREAD

**Issue by gutaker** [nicoduj/homebridge-harmony#64]
Hi,

today I've updated Raspbian. There were ~26 packages to update including, as I can remember, the `base-files`.
Now your awesome plugin stopped working and homebridge is giving me this output:

`0|homebridge  | [2/18/2019, 10:10:55 PM] [Harmony Hub Ultimate] Loading activities...
0|homebridge  | [2/18/2019, 10:10:55 PM] [Harmony Hub Ultimate] Error retrieving info from hub : 417 - {"code":"417"}`

I tried to lower the version to 0.4.0 and reinstalling the plugin completely and it's a NO-GO.

My HomeKit automation relies on your plugin to Turn On the TV when someone is coming home.
BTW: Everything was working fine with 0.4.1 version before system update.

Any clues?

**Comment by solomonj1963** [comment]
Ditto... Exactly...

**Comment by nicoduj** [comment]
Hi,

Can you try updating the file in the dependency harmony-websocket with the latest one in 
https://github.com/lopelex/harmony-websocket/blob/master/lib/harmony-websocket.js ?

417 means there is something that the server doesn’t like in header and I know there is a little error with an extra comma in the version published that was fixed after but as far as I knowit wasn’t a problem ...

**Comment by Stumah** [comment]
> Hi,
> 
> Can you try updating the file in the dependency harmony-websocket with the latest one in
> https://github.com/lopelex/harmony-websocket/blob/master/lib/harmony-websocket.js ?
> 
> 417 means there is something that the server doesn’t like in header and I know there is a little error with an extra comma in the version published that was fixed after but as far as I knowit wasn’t a problem ...

Hi,

I got the same issue. Updating the file didn't work for me...

**Comment by solomonj1963** [comment]
Thank you, I will try shortly. I’ve been out shopping and just saw your email.

Sent from my iPhone

On Feb 18, 2019, at 6:05 PM, Stumah <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Can you try updating the file in the dependency harmony-websocket with the latest one in
https://github.com/lopelex/harmony-websocket/blob/master/lib/harmony-websocket.js ?

417 means there is something that the server doesn’t like in header and I know there is a little error with an extra comma in the version published that was fixed after but as far as I knowit wasn’t a problem ...

Hi,

I got the same issue. Updating the file didn't work for me...

**Comment by pponce** [comment]
seeing the same error.  I made the 2 small changes by hand to the harmony-websockets.js file.
Didn't fix the error for me.

**Comment by solomonj1963** [comment]
No luck replacing the harmony-websocket.js.  I also noticed Logitech published new information about re-enabling XMPP [here](https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp).  Also tried that with no luck.

**Comment by BetoRn** [comment]
There was an update of the hub, I'm now on 4.15.250, this version reenabled xmpp but apparently broke web sockets

**Comment by solomonj1963** [comment]
Agreed.

On Feb 18, 2019, at 10:44 PM, Alberto Rojas <notifications@github.com<mailto:notifications@github.com>> wrote:


There was an update of the hub, I'm now on 4.15.250, this version reenabled xmpp but apparently broke web sockets

**Comment by Nastras** [comment]
For me, the problem is synonymous but only one of two hubs.

![b49bcb2e-b512-40e9-9247-0804958fc7ee](https://user-images.githubusercontent.com/27686185/52989172-822bd380-3402-11e9-9353-8e118ce884b2.jpeg)

**Comment by nicoduj** [comment]
Hi all, it seems that latest firmware broke the plugin. It is in the initial http connection, will have to check and reverse engeener their changes . Meanwhile revert or don’t update !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rheid** [comment]
The same on my site: Error retrieving info from hub : 417 - {"code":"417"}

**Comment by gutaker** [comment]
> Hi all, it seems that latest firmware broke the plugin. It is in the initial http connection, will have to check and reverse engeener their changes . Meanwhile revert or don’t update !
> 
> Sent with [GitHawk](http://githawk.com)

After downgrading Hub firmware to 4.15.210 everything worked flawlessly.
Thanks @nicoduj  - good job!

**Comment by Phoenix-DH** [comment]
It seems that the update was made to me automatically ... same problem ... argh ...
Thanks for working on it ...

**Comment by maisun** [comment]
How to disable auto upgrading?

**Comment by rheid** [comment]
@gutaker  How to downgrading the Hub Firmware?

**Comment by nicoduj** [comment]
@lopelex (thanks to him !) pushed an updated version of the lib that should work with latest hub firmware (as well as with old one). You can try to update dependencies / uninstall and reinstall my plugin. I will test this evening and release an update probably to force the move .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pponce** [comment]
Nice!
I have not done much testing but i can confirm the error is gone now.
And my scenes work again.
So it's looking good so far.

All i did was uninstall and re-install.
npm uninstall -g homebridge-harmony
npm install -g homebridge-harmony

**Comment by rheid** [comment]
@nicoduj also looks good on my site. huge thanks for unbelieving quick fix of the problem. I like your implementation very much!!

[2019-2-19 19:18:56] [HarmonyHub2] Kabel Fernsehen activated
[2019-2-19 19:19:00] [HarmonyHub2] INFO - onMessage : Refreshing activity to 29613497
[2019-2-19 19:19:07] [HarmonyHub2] Center activated
[2019-2-19 19:19:10] [HarmonyHub2] INFO - onMessage : Refreshing activity to 32038360

**Comment by nicoduj** [comment]
thanks to @lopelex https://github.com/lopelex/harmony-websocket for the quick update !

**Comment by lopelex** [comment]
thanks to @reneboer

**Comment by gutaker** [comment]
@rheid In case you'd like to downgrade despite the @lopelex solution, this can be done via MyHarmony desktop software only (AFAIK).

1. Open up the App, press Shift+F9 and you'll see `Update Remote` screen
2. Scroll down to the very bottom and you'll see `Firmware to enable XMPP. For devellopers onlyz`
3. Click `Update Firmware` and connect hub with USB
4. As soon as the software will detect the hub, the `Install` button becomes enabled.
5. Click `Install` and you're done!

@nicoduj and especially @lopelex - A BIG THANK YOU!

**Comment by gutaker** [comment]
Solution tested, thanks for @reneboer for input on @lopelex solution!

**Comment by DJay-X** [comment]
There was an Info that XMPP is disabled by default in 4.15.250

> By default, Harmony firmware will keep XMPP disabled. For those of you already using the special firmware version 4.15.210 with XMPP access, when your hub upgrades to 4.15.250, you can easily re-enable it by:
> 
> •   Perform a sync from your LCD screen based Harmony remote, by going to Menu > Settings > Sync Remote, or
> 
> •   From your Harmony app, go to: Menu > Harmony Setup > Add/Edit Devices & Activities > Remote & Hub > Enable XMPP

**Comment by misku** [comment]
Thank you all for the discussion and @lopelex for the fix. Using those changes I was able to make a python version working again: https://github.com/misku/pyharmony/commit/41d9691a7d4f4f3aa65989b5e281c8f714a1cef3
